### ISSUE TITLE
Cost per Incremental in a Deprivation Testing

### ISSUE THREAD

**Issue by ilaria-giunti** [facebookincubator/GeoLift#101]
I've already read all your posts about deprivation tests with GeoLift.

What I cannot understand is: how can I analyze the CPIC? Because if I turn off 3-4 regions or exclude them from my existing campaign, I don't know how much budget I would spend on those 3-4 regions.

How can I find out what my CPIC would have been?

**Comment by NicolasMatrices-v2** [comment]
Hi @ilaria-giunti! We have built a blog post specifically tackling the inverse GeoLift setup.

You can check this link that specifies our recommendation of how you should calculate a CPIC for treatment locations with inverse GeoLift.  Please check https://facebookincubator.github.io/GeoLift/blog/inverse-geolift/#calculate-the-treatments-cpic

Closing this out for now.  Feel free to reopen if you have further doubts or comments.
