### ISSUE TITLE
Test Geos pre selected

### ISSUE THREAD

**Issue by SG-GM** [facebookincubator/GeoLift#102]
We will have a geo targeted campaign in place in 6 cities. In developing a measurement plan we thought of using geo lift as a tool. However, since test markets are already chosen I have 2 Qs:
1. Can test markets be pre selected and control selected using geolift?
2. Can there be more than 1 test markets. If yes, how to operationalize it.
Thanks.

**Comment by NicolasMatrices-v2** [comment]
Hi @SG-GM!

1. Part of the main competitive advantages of GeoLift is that it helps you identify which are the best locations to build your treatment group.  This is not trivial and an ad hoc selection of them without looking at power curves can lead to some form of bias.  If you have already selected your treatment locations with some other criteria, you can run the GeoLiftPower function (i.e. check the walkthrough here https://github.com/facebookincubator/GeoLift/blob/main/vignettes/GeoLift_Walkthrough.md#note-you-could-repeat-this-process-for-the-top-5-treatment-combinations-that-come-out-of-geoliftmarketselection-with-increased-lookback-windows-and-compare-their-power-curves-we-will-do-it-only-for-chicago-and-portland-here).  This will tell you how your treatment behaves with respect to different effect sizes and what are the chances of detecting an effect. 

2. Yes, you can have more than 1 test market in the treatment group.  All you need to do is select the amount of locations you would like in the treatment (N parameter in GeoLiftMarketSelection).  If you have already selected a treatment, all you need is to specify those locations (locations parameter in GeoLift, GeoLiftPower).

Please feel free to reopen this if you have further doubts.
