### ISSUE TITLE
Setting the `cpic` with Sales Data (AKA transaction volume)

### ISSUE THREAD

**Issue by leoubbiali-mp** [facebookincubator/GeoLift#104]
Hi @ArturoEsquerra @NicolasMatrices-v2 

I wanted to ask a follow up question on the back of [this](https://github.com/facebookincubator/GeoLift/issues/85) issue

**Context** I'm setting up a geolift experiment where the `Y` metric is Revenue (total transaction volume in a geo)

**Question** is it correct to set the `cpic` = gross margin of the AverageTtransaction Volume? My concern is that we have a wide distribution of Average Transaction Volume

Am I missing something?

**Comment by ArturoEsquerra** [comment]
Hi @leoubbiali-mp! 

That's correct, when we're using revenue as the KPI, we should set the `cpic` parameter as `cpic = 1/iROAS` (where iROAS is the incremental return on ad spend). That way we are informing the model how much we should invest to obtain an additional/incremental dollar in revenue. 

And while this approach works really well for most GeoLift studies, if you are measuring products with widely different revenue distributions (for example, most products provide small profits while a handful of others drive most of it), then it could be a good idea to run a different experiment for each.

Does that make sense?

**Comment by leoubbiali-mp** [comment]
It does. Thanks @ArturoEsquerra 

In our case we have basically one product category whose value can be decided by the user (buy {amount} of {crypto} ). And the distribution of the Transaction Volume is pretty wide.

What would you suggest in this case?
I see two possible paths:
1. use the gross margin of the average transaction volume to set the CPIC
2. fallback on using `transactions` (aka conversions) to escape the complexity (losing information on the volume)

Any recommendation?

**Comment by leoubbiali-mp** [comment]
Hey @ArturoEsquerra @NicolasMatrices-v2  a gentle follow up on the above.
I think I can't reopen the issue. 
Looking forward to hearing from you 

cc:
