### ISSUE TITLE
Ability to Run GeoLift on data set of one location

### ISSUE THREAD

**Issue by robhannon** [facebookincubator/GeoLift#109]
## Running GeoLift on one location
Hi I am trying to run GeoLift on one location with a data set that only includes one location. Trying to simulate lift for one location to serve a single client. The number of dates is still quite large. Thank you for any help!

**Comment by ArturoEsquerra** [comment]
Hi @robhannon! You should be able to run the code for a single test location by setting the following parameter to 1: `N = c(1)` in our Market Selection functions.
