### ISSUE TITLE
Requesting the inclusion of basic data cleaning functions in GeoLift package

### ISSUE THREAD

**Issue by hsaxena1** [facebookincubator/GeoLift#111]
## Is your feature request related to a problem? Please describe.
This feature is being requested to overcome the challenges of creating manual data cleaning functions before a geolift analysis can be started on advertiser's data

## Describe the solution you'd like
I propose a two step solution here - 
First, we can include a function upfront that gives us a quick summary of the missing values in the raw data using every location x time index combination. 
Second, based on the summary provided in step 1 we recommend if those missing values can be replaced with 0s or interpolated numbers for the GeoDataRead function to work well.

## Describe alternatives you've considered
I have currently been using my own functions to have a glance at the data trends/missing values and then making the decision to whether replace those values with 0s or drop them from the analysis completely.

## Additional context
None

**Comment by JussanN** [comment]
Hi, thank you for your request. This is a nice-to-have feature but it doesn't block you to use GeoLift functions. If possible, I recommend you to build this feature and collaborate with the package improvement. I'm closing this issue for now. Thank you.
