### ISSUE TITLE
Bug in Analysis for the design of a new experiment after another experiment - Change the pre-period

### ISSUE THREAD

**Issue by ilaria-giunti** [facebookincubator/GeoLift#117]
We have run 2 experiments for a client in the last 2 months but if we design a new experiment it will be affected by the results of these two experiments.

Can I change the pre-period in order not to be affected by these two experiments? 
What if I want to analyze the impact of my experiment and compare it with a period when I didn't run any experiment?

Does it make any sense for you?
  
```
Output goes here
```

## Additional context
  Add any other context about the problem here. (like proxy settings, network setup, overall goals, etc.)

**Comment by NicolasMatrices-v2** [comment]
Hi @ilaria-giunti, when deciding on a new GeoLift design after you've run one, we suggest you replace the treatment series that were affected during the test with their counterfactual.  
We have implemented functions that can help you do this.  Check this PR https://github.com/facebookincubator/GeoLift/pull/112.  It has a clear example that you can leverage to adjust your dataset properly.

For the future, please refer these types of questions to our fb group (https://www.facebook.com/groups/fbgeolift).  Closing this issue out for now.
