### ISSUE TITLE
Using GeoLift to detect a metric drop given an intervention 

### ISSUE THREAD

**Issue by LeoUbbiali** [facebookincubator/GeoLift#12]
Hey FB team,

I'm Leo from Babylon Health. Thanks for building this package 🙏 . We have been doing geo-experiments with CausalImpact/diff-in-diff and we are now excited to try the FB solution.

##Question

is the hypothesis testing one-tailed or two-tailed? Can I use it to detect a drop in conversions given an intervention (stop of a "always on" historical marketing campaign")?

##Use case details:  

-  Granularity of geo: zipcode 
-  metric: conversion
-  the campaign has been running for almost a year (can be considered the steady-state)

Thanks in advance for your help

**Comment by ArturoEsquerra** [comment]
Hi @LeoUbbiali, thank you very much for trying GeoLift out! While the default test looks for both positive and negative effects, you can change this with the `stat_test` parameter of the `GeoLift()` function. It accepts the following values:

- Total: Test for positive and negative effects (absolute value of the effects)
- Negative: One-way test against negative effects
- Positive: One-way test against positive effects

Moreover, you can definitely run it to detect whether the stop of the "always-on" campaign had a significant effect on our test regions. For optimal results, we recommend using daily data (if available).

**Comment by LeoUbbiali** [comment]
great news! Thank you so much for the quick answer @ArturoEsquerra !

on the daily data reccomendation: It's available but the volume by `zipcode` is very low and highly variable.
For this reason I am grouping by week.

Any feedback on this decision criteria is welcome.

**Comment by ArturoEsquerra** [comment]
Hi again @LeoUbbiali! Fortunately, you have a robust amount of historical weekly data so that approach should work great too! In general, we recommend a year of historical weekly data or ~100 observations of daily data.

**Comment by LeoUbbiali** [comment]
Perfect 👍 
Thank you so much @ArturoEsquerra

**Comment by AdimDrewnik** [comment]
@LeoUbbiali Are you still using GeoLift in your work? Can you share a case study/code/data for you geo test that you described in this thread? 
I am also having an always on campaign and I suspect it does nothing but no one has courage to turn it off and see, so maybe a geo lift test on limited number of geos that will be switch off would be possible.
