### ISSUE TITLE
CI and P-values Contradict

### ISSUE THREAD

**Issue by BrianMiner** [facebookincubator/GeoLift#122]
It seems there is an issue with confidence intervals and p-value from GeoLift

Running the walk through code in https://facebookincubator.github.io/GeoLift/docs/GettingStarted/Walkthrough but adding confidence intervals:

```
GeoTest <- GeoLift(Y_id = "Y",
                   data = GeoTestData_Test,
                   locations = c("chicago", "portland"),
                   treatment_start_time = 91,
                   treatment_end_time = 105,
                   ConfidenceIntervals = TRUE)

summary(GeoTest) 
```
Produces the following where the cumulative treatment effect is highly significant but the 90% CI for this lift is not? And the CI is pretty enormous.

![image](https://user-images.githubusercontent.com/8807554/205474374-8acf0779-7db8-487f-b74f-605cd290bc29.png)

How to reconcile this?

**Comment by BrianMiner** [comment]
Hmm. Yeah that's definitely an issue. I didnt dig in enough to see if gsynth is an option instead as I know all bootstrap samples are  exposed and a p-value of sorts as well as any CI can be generated of course from those.

**Comment by riabenko** [comment]
This is not resolved - the issue can be easily demonstrated on the walkthrough example data:

```
GeoTest <- GeoLift(Y_id = "Y", data = GeoTestData_Test, locations = c("chicago", "portland"), treatment_start_time = 91, treatment_end_time = 105, ConfidenceIntervals = TRUE, conformal_type = "block", model = 'ridge')
summary(GeoTest)

##################################
#####     Test Statistics    #####
##################################

* Average ATT: 156.805
* Percent Lift: 5.5%
* Incremental Y: 4704
* P-value: 0.03
* 90% Confidence Interval: (-3861.285, -3861.285)
```

Trying different values of grid_size does not help.

**Comment by alexanderhe88** [comment]
Confirmed that it is not solved today:

GeoTest <- GeoLift(Y_id = "Y",
                   data = GeoTestData_Test,
                   locations = c("IL"),
                   treatment_start_time = 33,
                   treatment_end_time = 53,
                   model = 'Ridge',
                   alpha = 0.10,
                   ConfidenceIntervals = TRUE)

#####     Test Statistics    #####
##################################

Percent Lift: 1.3%
Incremental Y: 2710
90% Confidence Interval: (-67765.067, -4366.216)
Average Estimated Treatment Effect (ATT): 129.026
The results are significant at a 90% level. (TWO-SIDED LIFT TEST)
