### ISSUE TITLE
Running a geo-test w/ where hold-outs have typical levels of spend and treatment receives increased spend

### ISSUE THREAD

**Issue by djolear** [facebookincubator/GeoLift#129]
Hello - 

Thanks for putting together this excellent package.

I'm wondering if this package could be use to design a geo-test where the hold-out markets receive their typical level of spend and the treatment markets receive new additional spend. In this design, all markets would receive some ad spend, but we would be measuring the incremental impact of additional spend above and beyond what we typically spend.

Is this a supported use-case for the package?

**Comment by NicolasMatrices-v2** [comment]
Hi @djolear thanks for your question! 

That's correct, GeoLift can also be used to design an experiment where the control group shows ads of a certain campaign and the treatment group shows ads from that campaign and another one as well.  Or you could also just move up the investment in the treatment regions and test the elasticity of that media channel.

Sharing this case study from Mixtiles, an Israeli company that wanted to understand the impact that running a full funnel campaign (in treatment) had vs what they were currently running (in control).  https://www.facebook.com/business/measurement/case-studies/mixtiles.

Closing this out for now. Feel free to reopen if you would like to follow up.

**Comment by djolear** [comment]
Hi @NicolasMatrices-v2, thanks for getting back to me (and for the awesome packaged)!

This is helpful background. I will definitely take a look at the case study.

I was wondering if using GeoLift for this purpose invalidates any of the outputs of the functions in the package or requires some kind of differential interpretation?

Would the following approach make sense to you:

If we're using the example in the walkthrough, could we use the exact same set up and dataset, but rather than thinking of the budget for this test as the only money that is being spent on marketing, we could think of that budget as the incremental budget being spent on marketing? So the total cost of marketing would be whatever we are currently spending + the budget for the experiment and the hold-out regions aren't so much hold-out regions as they are regions where we won't alter spend?

And in a semi-related question, am I right in seeing that we could use the Multi-Cell version to create a test where we have three variations in spend but all for the same campaign 1) some regions that receive no spend, 2) some that receive normal spend, and 3) some that receive increased spend? Just confirming because I think the walkthrough is focused on multi-cell for multi-channel tests.

Thanks!
