### ISSUE TITLE
Real-world implementation problems

### ISSUE THREAD

**Issue by albertsalgueda** [facebookincubator/GeoLift#130]
Dear developers,

I hope this message finds you well. I am writing to express my gratitude for the geolfit library and raise some concerns about its practical implementation.

I would like to inquire about budget allocation in the experimental plan. Once we have the experimental design ready, the marketing specialist may wonder how to allocate the budget. For example, suppose there are three treatment geos and a budget of $3k for an experiment duration of four weeks. Should the budget be allocated proportionally, such as $1,000 for each geo and $250/week, or should it be allocated depending on historical budget or geo market size? Any guidance or best practices on this matter would be highly appreciated.

Thank you for your time and efforts in developing the geolfit library. I look forward to hearing your feedback and suggestions.

Best regards,
Albert

**Comment by ArturoEsquerra** [comment]
Hi @albertsalgueda, thank you for reaching out to us and for using GeoLift!

This is a really good question. Most digital platforms will work best when they are allowed some freedom to optimize the spending of the budget. With this in mind, we would recommend leaving the $3000 budget for the set of test regions and let the platform spend it according to the best-suited optimization event/conversion. Does that make sense?
