### ISSUE TITLE
Interpreting GeoLift power analyses in context of test to ramp up spend

### ISSUE THREAD

**Issue by djolear** [facebookincubator/GeoLift#131]
Hi @NicolasMatrices-v2, thanks for getting back to me on [this issue](https://github.com/facebookincubator/GeoLift/issues/129) (and for the awesome package)!

This is helpful background. I will definitely take a look at the case study.

I didn't have permissions to re-open the issue, but had one follow-up question.

I was wondering if using GeoLift for this purpose invalidates any of the outputs of the functions in the package or requires some kind of differential interpretation?

Would the following approach make sense to you:

If we're using the example in the walkthrough, could we use the exact same set up and dataset, but rather than thinking of the budget for this test as the only money that is being spent on marketing, we could think of that budget as the incremental budget being spent on marketing? So the total cost of marketing would be whatever we are currently spending + the budget for the experiment and the hold-out regions aren't so much hold-out regions as they are regions where we won't alter spend?

And in a semi-related question, am I right in seeing that we could use the Multi-Cell version to create a test where we have three variations in spend but all for the same campaign 1) some regions that receive no spend, 2) some that receive normal spend, and 3) some that receive increased spend? Just confirming because I think the walkthrough is focused on multi-cell for multi-channel tests.

Thanks!

**Comment by ArturoEsquerra** [comment]
Hi @djolear. Thanks for reaching out to us and for using the GeoLift package!

Those are great questions:

1. You're correct! The way the budget recommendation in the GeoLift Market selection functions work is by suggesting the amount of **incremental** spend needed on test regions. In the simplest cases where control regions are restricted from any ads/investment, the recommended budget is really straightforward as it would represent the **total** budget needed for the test. However, in experimental designs where the control regions continue to receive BAU spend, the budget suggested by `GeoLiftMarketSelection()` represents the **additional** spend on top of BAU needed to execute a well-powered test. We commonly refer to these designs as "heavy-up tests" and they're really useful to analyze the incremental effect of a new strategy. A frequent test design is to measure the incremental effect of Branding campaigns for performance-heavy advertisers. Here, the advertiser would run their performance campaigns as usual for all regions and a set of test locations would receive branding campaigns on top of the BAU. In this scenario, the budget recommendation would show us how much we should spend on the branding campaigns (it's important to make sure that the CPIC we use for the calculation reflects the effectiveness of these branding campaigns.).
2. Absolutely! These "media pressure" tests are extremely useful to gauge the ideal spend for a channel and measure its elasticity. For example, you could set a 2-cell test in which the control region would receive no spend, test group A would receive the usual spend (100%), and cell B would receive 150% spend.

Best,
Arturo

**Comment by djolear** [comment]
Awesome, thank you so much @ArturoEsquerra !
