### ISSUE TITLE
Estimated investment much lower than the budget I provide

### ISSUE THREAD

**Issue by djolear** [facebookincubator/GeoLift#133]
Hi folks!

I have another question for you. I'm simulating a test where I have a budget of $100k, a cpic of $5, and I want to be able to detect an effect as low as 0.01.

When I run the `GeoLiftMarketSelection`, all of the market selections provide an estimated investment that is much lower than the budget I provided. The estimated investment is often less than $5,000. I would have thought that using a larger budget would lead to a test with more statistical power. Would you help me understand why the estimated investment is so much lower than the budget I provide? 

One thought I have is that if I want to detect a lift of 1%and my cpic is $5, maybe the function thinks that I don't need that much money to be able to generate a 1% lift in conversions and so the function recommends a relatively inexpensive test, but would like to confirm my understanding of what's happening here. 

Thank you!

**Comment by raphaeltamaki** [comment]
Hey @djolear 
In the function `GeoLiftMarketSelection` the `budget` input is only used to filter for the options in which the required investment is below the budget. If no other constraints are applied, the market selections outputted are those where it was possible to achieve a power greater than 80%.

Regarding the relation of greater investment leading to greater (considering the same selection of market), that is true. But the "Cost per additional confidence" rapidly increases at the end, as such, most of the time it is not worth investing all the budget.
For reference, the units of uncertainty decreased on the estimate (Y) per investment (X) usually look like the curve below: 
<img width="650" alt="Screenshot 2023-06-23 at 11 26 33" src="https://github.com/facebookincubator/GeoLift/assets/125194254/39d0b31a-0332-40c6-91e3-aaaff288270b">
