### ISSUE TITLE
Integrating historical spend into MarketSelection process

### ISSUE THREAD

**Issue by RhysJackson** [facebookincubator/GeoLift#136]
## Is your feature request related to a problem? Please describe.
When running an inverse incrementality test, there's an extra step required to check whether there is enough existing spend in the test locations to meet or exceed the investment required for the experiment. When the investment requirement is not met, there is an additional calculation to estimate the extra investment required in the control. This is documented in more detail here: https://facebookincubator.github.io/GeoLift/blog/inverse-geolift#determine-budget-for-the-test

## Describe the solution you'd like
I would like the option to provide historical spend data for the marketing activity we plan to test and, as part of the market selection process, for GeoLift to:
a) Estimate how much money is typically spent in the test locations for the experiment duration
b) Compare the estimated spend to the required investment and determine if it will be sufficient
c) If the test group spend doesn't exceed the required investment, then estimate the extra spend required in the control group
d) Have the option for this data to influence the experiment ranking. For example, by favouring experiments with test locations that meet or exceed the investment requirement

## Describe alternatives you've considered
This process is currently is currently carried out manually after markets have been selected. It would save time and improve consistency to have it featured as part of the package.

## Additional context
N/A

**Comment by raphaeltamaki** [comment]
Hi @RhysJackson 

Thank you very much for your post, and it is great to see that you know so much about the package to find your solution around your problem. We will add this point to the roadmap, but - just for visibility - the development team has restricted resources to invest in GeoLift for now, so it will take some time until you see this feature released
