### ISSUE TITLE
trouble installing augsynth in RStudio

### ISSUE THREAD

**Issue by LMiddles** [facebookincubator/GeoLift#141]
## Bug description
code run 
remotes::install_github("ebenmichael/augsynth")

error message
   '"C:\Users\xxx~1\AppData\Local\Programs\R\R-42~1.1/bin/x64/Rterm.exe"' is not recognized as an internal or external command,
   operable program or batch file.
Error: Failed to install 'augsynth' from GitHub:
  ! System command 'Rcmd.exe' failed

Checked if available for current RStudio version
pkgbuild::with_build_tools(install.packages("ebenmichael/augsynth", type = "source"))
result
Warning in install.packages :
  package ‘ebenmichael/augsynth’ is not available for this version of R

Is this an issue with the version of R or something to do with permissions on my pc or .... ? (i am on a work device)

## Session information

R version 4.2.1 (2022-06-23 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19044)

## Reproduction steps

library(remotes)
library(devtools)
library(pkgbuild)
library(pkgconfig)
library(usethis)

> pkgbuild::check_rtools(TRUE)
Found in Rtools 4.2 installation folder
[1] TRUE
> pkgbuild::has_rtools(TRUE)
Found in Rtools 4.2 installation folder
[1] TRUE
> pkgbuild::has_build_tools(debug=TRUE)
Found in Rtools 4.2 installation folder
[1] TRUE
> devtools::find_rtools(debug=TRUE)
Found in Rtools 4.2 installation folder
[1] TRUE

install.packages("C:/Users/xxx/Downloads/LowRankQP_1.0.5.tar.gz", repos = NULL, type = "source")

'"C:\Users\xxxI~1\AppData\Local\Programs\R\R-42~1.1/bin/x64/Rterm.exe"' is not recognized as an internal or external command,
operable program or batch file.
Warning in install.packages :
  installation of package ‘C:/Users/xxx/Downloads/LowRankQP_1.0.5.tar.gz’ had non-zero exit status

install.packages("C:/Users/LiamMiddleton/Downloads/Synth_1.1-6.tar.gz", repos = NULL, type = "source")
'"C:\Users\xxxI~1\AppData\Local\Programs\R\R-42~1.1/bin/x64/Rterm.exe"' is not recognized as an internal or external command,
operable program or batch file.
Warning in install.packages :
  installation of package ‘C:/Users/xxx/Downloads/Synth_1.1-6.tar.gz’ had non-zero exit status

remotes::install_github("ebenmichael/augsynth")
--
devtools::install_github("ebenmichael/augsynth")

## Expected behavior
Unable to install geolift due to pre requisites not installing 
  
```
Output goes here
```

## Additional context
  Add any other context about the problem here. (like proxy settings, network setup, overall goals, etc.)

**Comment by ArturoEsquerra** [comment]
Hi @LMiddles, this recent issue is caused by a dependency that has recently been removed from CRAN. We recommend following the [updated installation instructions](https://github.com/facebookincubator/GeoLift#installing-geolift) to get `synth`, `LowRankQP`, and `augsynth`.
