### ISSUE TITLE
Feature Request: adding parameters like include_markets and exclude_markets to MultiCellMarketSelection

### ISSUE THREAD

**Issue by rrappa1** [facebookincubator/GeoLift#172]
## Is your feature request related to a problem? Please describe.
Currently, it seems that there isn't a way for the MultiCellMarketSelection function to exclude and include specific markets, unlike the GeoLiftMarketSelection function, which has the include_markets and exclude_markets parameters. 

## Describe the solution you'd like
Would it be possible to add parameters/functionality to the MultiCellMarketSelection function that allow users to specify markets that should be excluded as well as included? (Included by cell, ideally.)

## Describe alternatives you've considered
Writing a custom solution for this or using a different open-source tool.

**Comment by JussanN** [comment]
Hi @rrappa1 thank you for your request. This a nice-to-have feature but it doesn't block you to use GeoLiftMarketSelection. For now, I suggest you to not include in the input dataset any market you don't want to take into account in the simulations. Feel free to collaborate and submit the code for this feature so we can review it. I'm closing this issue for now. Thank you.

**Comment by rrappa1** [comment]
Sounds good, thank you for getting back to me!
