### ISSUE TITLE
"there is no package called ‘GeoLift’"

### ISSUE THREAD

**Issue by gfi1ippou** [facebookincubator/GeoLift#173]
## Bug description
Although I have used geolift, I can't access it now. Library can not be found

## Rstudio version
Version 2023.09.1+494 (2023.09.1+494)

I have reinstalled R and R studio. 

I use a MacBook Pro, 2 GHz Quad-Core Intel Core i5, 16 GB 3733 MHz LPDDR4X

## Session information
A version of this package for your version of R might be available elsewhere,
see the ideas at
https://cran.r-project.org/doc/manuals/r-patched/R-admin.html#Installing-packages
> library(GeoLift)
Error in library(GeoLift) : there is no package called ‘GeoLift’
> install.packages("GeoLift")
Warning in install.packages :
  package ‘GeoLift’ is not available for this version of R

A version of this package for your version of R might be available elsewhere,
see the ideas at
https://cran.r-project.org/doc/manuals/r-patched/R-admin.html#Installing-packages
> library(GeoLift)
Error in library(GeoLift) : there is no package called ‘GeoLift’
## Reproduction steps
  Enter steps to reproduce the behavior.

**Comment by SanjayShetty01** [comment]
The package is not available on CRAN. Please try the following, ensuring that you have R 4.0.0 or a later version installed.

```r 
install.packages("remotes", repos='http://cran.us.r-project.org')
remotes::install_github("ebenmichael/augsynth")
remotes::install_github("facebookincubator/GeoLift")
```
