### ISSUE TITLE
MultiCellMarketSelection Not Plotting Summary

### ISSUE THREAD

**Issue by titubs** [facebookincubator/GeoLift#184]
@JussanN @kesemadi

Hello, 
I am using MultiCell function and I am not getting a summary output. This is not expected:

<img width="1285" alt="Screen Shot 2024-03-20 at 10 17 13 PM" src="https://github.com/facebookincubator/GeoLift/assets/107452474/0025e96f-ee1f-4d84-847e-01c4564a598c">

Secondly, I wanted to check if I can do an inverse Geolift by defining N=5, meaning I will use these as holdout (as suppose to treatment) and then the ATT will be flipped. Can I just flip the script or are there any implications?

**Comment by JussanN** [comment]
Hi @titubs Please run Markets (object) in a new line after the function as explained in the walkthrough (link below) to see the summary of your results.

https://facebookincubator.github.io/GeoLift/docs/GettingStarted/MultiCellWalkthrough#2-finding-test-markets-with-multicellmarketselection

I'm closing this issue for now. Thank you.
