### ISSUE TITLE
Question about effects of previous campaigns.

### ISSUE THREAD

**Issue by niramay447** [facebookincubator/GeoLift#185]
when we are creating the test control, how do we capture and/or exclude the impact of past campaigns(not geo tests) that might have run in some of the markets.

**Comment by titubs** [comment]
@niramay447  I tried to tag you in my original Issue POST here https://github.com/facebookincubator/GeoLift/issues/199 but i dont think it worked, so I tried through an old/closed post. I hope you can help me, thanks!
