### ISSUE TITLE
Error in installing package

### ISSUE THREAD

**Issue by puleengupta** [facebookincubator/GeoLift#188]
I am getting an error message while loading the package 
Looks like this is because of some recent changes in Description file

Error Message :
Malformed Authors@R field:
     <text>:18:5: unexpected symbol
   17:            email = "michaelkhalil@meta.com")
   18:     person
           ^
   
   See section 'The DESCRIPTION file' in the 'Writing R Extensions'
   manual.
Error: Failed to install 'GeoLift' from GitHub:
  ! System command 'Rcmd.exe' failed

**Comment by JussanN** [comment]
Hi @puleengupta thank you very much for letting us know. 
We just fixed the issue and now you should be able to install the package. Could you confirm that this the case please? 
Thank you in advance. 
Best regards,
Jussan

**Comment by puleengupta** [comment]
Hi @JussanN 
Thanks for your revert here
The previous error is resolved but I am getting more error

New Error :

Installing package into ‘C:/Users/GuptaPu/AppData/Local/R/win-library/4.2’
(as ‘lib’ is unspecified)
ERROR: dependency 'MarketMatching' is not available for package 'GeoLift'
* removing 'C:/Users/GuptaPu/AppData/Local/R/win-library/4.2/GeoLift'
Warning message:
In i.p(...) :
  installation of package ‘C:/Users/GuptaPu/AppData/Local/Temp/Rtmps7pshm/file5a3851927a1a/GeoLift_2.7.4.tar.gz’ had non-zero exit status

**Comment by JussanN** [comment]
Hi @puleengupta 

Could you provide some more information on your R session? Sharing the output from sessionInfo() would be great!

Thank you in advance, 

Jussan

**Comment by puleengupta** [comment]
Hi
Below is the required info
R version 4.2.2 (2022-10-31 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19045)

Matrix products: default

locale:
[1] LC_COLLATE=English_India.utf8  LC_CTYPE=English_India.utf8    LC_MONETARY=English_India.utf8
[4] LC_NUMERIC=C                   LC_TIME=English_India.utf8    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
 [1] ps_1.7.3          prettyunits_1.2.0 crayon_1.5.2      withr_3.0.0       rprojroot_2.0.3  
 [6] R6_2.5.1          cli_3.6.0         curl_5.0.0        remotes_2.5.0     rstudioapi_0.14  
[11] callr_3.7.3       desc_1.4.2        tools_4.2.2       compiler_4.2.2    processx_3.8.0   
[16] pkgbuild_1.4.0    sessioninfo_1.2.2

**Comment by puleengupta** [comment]
Hi @ProxyCausal 
Thanks for you feedback here .I think it should with my version as per the R version requirements mentioned in the documentation

**Comment by puleengupta** [comment]
Hi @JussanN 
Could you or anyone else provide help here

**Comment by JussanN** [comment]
Hi @puleengupta are you following the Getting Started page? https://facebookincubator.github.io/GeoLift/docs/GettingStarted/InstallingR

During the installation of GeoLift, I suggest you to press Enter each time a question is asked.

I'm adding in this discussion @raphaeltamaki who will be able to continue the support as I'll be on vacation. 

Let us know if one of the recommendations above worked for you. 

Thank you.

**Comment by puleengupta** [comment]
Hi @JussanN  and @raphaeltamaki 
Yes, I followed the mentioned instructions but still getting this error.

**Comment by puleengupta** [comment]
Hi @JussanN 
"I finally managed to install Geolift. The problem was that I was using R version 4.2, but Geolift requires the Market Matching function, which can only run on version 4.3 or higher.

I also had to install many other packages from CRAN and GitHub due to numerous dependencies."
Thank you for all the support and Happy vacation!

**Comment by JussanN** [comment]
Hi @puleengupta thank you very much for sharing the solution that worked for you. I'm closing this issue.
