### ISSUE TITLE
feature request: non-inferiority test hypothesis

### ISSUE THREAD

**Issue by LeoUbbiali** [facebookincubator/GeoLift#19]
Hi guys,

I'm opening this issue to ask if it would be possible to add a `non-inferiority` /`equivalence` option at the inference step.

**Use Case:**  

- a company has been running  `{marketing_campaign/channel]` for the last N periods 
- hypothesis: switching the campaign/channel off would not impact the target metric negatively ( with a `non-inferiority margin`)

**Context:** 
assuming that we are in a frequentist setting, the test could be set up either as a `superiority` or `inferiority` test. 
Hence, if we don't find significant results we can't state that the test areas are 'non-inferior' or 'equivalent' to the counterfactual but we can only affirm that there is not enough evidence for stating 'superiority' or 'inferiority'.

**Comment by NicolasMatrices-v2** [comment]
Hi @LeoUbbiali thanks for the feedback! 

If I understood you correctly, this is implemented under the stat_test parameter for the `GeoLift` method. You can check these lines for documentation details on how to implement it https://github.com/facebookincubator/GeoLift/blob/main/R/GeoLift.R#L2564-L2570.  This runs a one tailed test on the estimator, and you can decide what is the alternative hypothesis you would like to test:
- stat_test = 'positive' for H0: ES <= 0 & HA: ES > 0
- stat_test = 'negative' for H0: ES >= 0 & HA: ES < 0
- stat_test = 'total' for H0: ES == 0 & HA: ES != 0

Best

**Comment by LeoUbbiali** [comment]
Hi @NicolasMatrices-v2  thanks for the prompt reply and the reference in the code. I really appreciated that.

My understanding is that the 3 options are for superiority (1), inferiority (2) and two-tailed (3)
The idea would be to have other two options:

- stat_test = 'equivalent' for ES != 0 & HA: ES = 0 
- stat_test = 'non-inferior for ES <0 and HA: ES >= 0

for both of these options, we would need another parameter: the `non-inferiority/equivalence margin`
It defines a range of values for which the efficacies are “close enough” to be considered equivalent/non-inferior.

**principle:** if I want to test the "turning off" of a campaign I could not set `stat_test= 'negative' ` and then claim success if I don't find statistical significance as "absence of evidence is not evidence of absence".

(note: success is defined as "turning off the campaign does not impact the target metric")

It would be a directional insight but not statistically watertight 

Let me know your thoughts. 

*Resources*
[Understanding Equivalence and Noninferiority Testing
](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3019319/)

**Comment by LeoUbbiali** [comment]
Hi @NicolasMatrices-v2  @ArturoEsquerra .
checking in to see if you have any thoughts on the above 😃 

Thanks,

Leo

**Comment by LeoUbbiali** [comment]
Hi @NicolasMatrices-v2  @ArturoEsquerra . 
Gentle follow up on the above. It would be great to hear your thoughts.

Thanks,

Leo

**Comment by NicolasMatrices-v2** [comment]
Hi @LeoUbbiali, sorry for the late reply.

Thanks for shedding more light on what you are suggesting.  We are having some trouble understanding the concrete business value that this new Hypothesis Test will add to GeoLift, because of the following reason.

In the cases we have observed, having a Treatment effect = 0 is not something that we would like to detect.  The Null Hypothesis should include the zero, as GeoLift is a tool designed to detect Treatment Effects over the Treated that are different from zero.  This is usually the case for advertising, where the baseline is that the treatment has no effect and we intend to observe that the treatment actually had an effect.

Could you help us understand what is the concrete business case that you would like to solve by adding this Hypothesis Test to GeoLift? We need to be able to size the impact of this feature request.

**Comment by LeoUbbiali** [comment]
Hi @NicolasMatrices-v2, thanks for the reply and the context on feature sizing, I totally get it

Happy to provide more context on the business case.

*Hypothetical scenario*: 

*the business has been running _campaignX_ consistently for the last _T_ weeks measuring the impact  on the target metric only via attribution/other methods not designed to detect incrementality

***Objective** The data team wants to measure what's the impact of switching off _campaignX_ on the target metric so that if the campaing is not incremental they can eventually recommend to switch off/ amend  _campaignX_

I hope this can help clarify the picture.
If you have any further questions, I'm happy to expand further.

Thanks,

Leo

**Comment by LeoUbbiali** [comment]
Hi @NicolasMatrices-v2 ,

thank you so much for your explanation - it makes sense to me and I will proceed with this hypothesis framing.
