### ISSUE TITLE
Availability of Python Geolift walkthrough

### ISSUE THREAD

**Issue by Vishnurprasad** [facebookincubator/GeoLift#193]
Hi All,

I had earlier seen a python notebook which could be used to invoke the R libraries of Geolift. This library seems to have been deleted from the repository now.  Was there a specific reason why this was deleted?

Thanks,
V

**Comment by JussanN** [comment]
Hi @Vishnurprasad,

The Python Notebook can be found under the GeoLiftPython branch: https://github.com/facebookincubator/GeoLift/tree/GeoLiftPython

Best,

Jussan

**Comment by Vishnurprasad** [comment]
Thank you Jussan!
