### ISSUE TITLE
ERROR: dependencies 'LiblineaR', 'osqp' are not available for package 'augsynth'

### ISSUE THREAD

**Issue by SaiAditya2595** [facebookincubator/GeoLift#196]
## Bug description
  I am getting this error " ERROR: dependencies 'LiblineaR', 'osqp' are not available for package 'augsynth' when I am trying to install Geolift in my Rstudio.

## Session information
  > sessionInfo()
R version 4.1.0 (2021-05-18)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 22621)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                           LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
 [1] processx_3.7.0    compiler_4.1.0    R6_2.5.1          rprojroot_2.0.3   cli_3.6.1         prettyunits_1.2.0 tools_4.1.0      
 [8] withr_3.0.1       rstudioapi_0.14   curl_4.3.2        crayon_1.5.3      remotes_2.5.0     callr_3.7.2       pkgbuild_1.3.1   
[15] ps_1.7.1         

## Reproduction steps
 I have followed the installation manual from here. 
https://facebookincubator.github.io/GeoLift/docs/GettingStarted/InstallingR.  I am getting the above error when I am trying to run 

remotes::install_github("ebenmichael/augsynth"). I have tried to install it separately but no use. 

Please help me if anyone is familiar with it? Thanks in advance

Aditya

**Comment by SaiAditya2595** [comment]
Sorry to update it here. I am getting this error while running remotes::install_github("facebookincubator/GeoLift") line from the documentation. 
ERROR: dependency 'MarketMatching' is not available for package 'GeoLift'

**Comment by JussanN** [comment]
Hi @SaiAditya2595 did you solve the first issue you mentioned when installing augsynth package? About the error when installing GeoLift package, can you try to install it again and share the step-by-step you went through? Thank you in advance.

**Comment by SaiAditya2595** [comment]
@JussanN Thank you so much for your response. I have upgraded my R package to 4.4.1 and able to install Geolift() package without any issue.

**Comment by JussanN** [comment]
Hi @SaiAditya2595 glad that you were able to solve it. Thank you for the update.

**Comment by titubs** [comment]
@JussanN I tried to tag you in my original Issue POST here https://github.com/facebookincubator/GeoLift/issues/199 but i dont think it worked, so I tried through an old/closed post. I hope you can help me, thanks!
