### ISSUE TITLE
Error running NumberLocations function

### ISSUE THREAD

**Issue by gibrano** [facebookincubator/GeoLift#31]
Hi GeoLift team,

I'm having problem running the GeoLift Walkthrough, with the function NumberLocations:

`
library(GeoLift)

data(GeoLift_PreTest)

GeoTestData_PreTest <- GeoDataRead(data = GeoLift_PreTest,
                                   date_id = "date",
                                   location_id = "location",
                                   Y_id = "Y",
                                   format = "yyyy-mm-dd")
head(GeoTestData_PreTest)

GeoPlot(GeoTestData_PreTest,
        Y_id = "Y",
        time_id = "time",
        location_id = "location")

resultsNum <- NumberLocations(data = GeoTestData_PreTest,
                              Y_id = "Y",
                              location_id = "location",
                              time_id = "time",
                              n_sim = 500,
                              treatment_periods = 15,
                              plot = TRUE,
                              power = 0.8,
                              alpha = 0.1,
                              fixed_effects = TRUE,
                              ProgressBar = TRUE)
`

![image](https://user-images.githubusercontent.com/21179249/152056253-8360c072-8432-4f48-8d5c-bffa72e4c2b8.png)

**Comment by ArturoEsquerra** [comment]
Hi Gibran,

Thanks for trying GeoLift out and reaching out to us!

Could you provide us with additional information to replicate this issue? For example, the output from `sessionInfo()` would be very useful.

**Comment by gibrano** [comment]
Hi Arturo,

Sure, below the output:

![image](https://user-images.githubusercontent.com/21179249/152217635-24696aeb-8e82-42ca-b776-b876feff0347.png)

**Comment by ArturoEsquerra** [comment]
Hi again Gibran,

We just confirmed that this error is related to a **very** recent change in `tidyr` which just landed yesterday. While we perform a complete fix of this issue, I recommend using the previous version of this package (1.1.4). One way to accomplish this is by running:

`packageurl <- "http://cran.us.r-project.org/src/contrib/Archive/tidyr/tidyr_1.1.4.tar.gz"`
`install.packages(packageurl, repos=NULL, type="source")`

Thanks a lot for raising the issue!

**Comment by gibrano** [comment]
Nice!

It's working now, thank you so much.
