### ISSUE TITLE
Feature Request: Handling of multiple test cells

### ISSUE THREAD

**Issue by michaelwexler** [facebookincubator/GeoLift#35]
A simple test is a basic A/B,  a single or few test geos vs. a single or few control geos.  However, we often want to test variations, such as 50% more spend and 100% more spend,  each vs. control, or Radio vs. TV. vs. both vs. control.  

In these cases, to help with planning, the tool could either ask for # of test conditions needed and provide either a) test and control sets, deduping test geos (this means multiple control measurements, as they may all be different for each test set), or b) test sets that are equivalent enough to be compared, and a single (synthetic) control which can be used as a baseline for all conditions.

I'm assuming this is a natural extension of the current tooling, but I could be (very) wrong.

**Comment by marguegit** [comment]
Hi @sohammarin , 

thank you for sharing your approach this is really smart and useful. Small remark / question on step 3. In my opinion, it's also necessary to exclude the markets which are part of the weights for the control in step 2 for B markets. If not, there is a risk that you would expose A markets (from the adjusted set up of step 3) to A treatment, which would not be valid as a true control anymore for B. 

What do you think?

**Comment by ArturoEsquerra** [comment]
Hi @marguegit, @sohammarin, and @michaelwexler. We're excited to announce that today we rolled-out a new version of the code (v2.5) which includes Multi-Cell capabilities!
