### ISSUE TITLE
Errors in NumberLocations & GeoLiftPower - can't convert from double to integer

### ISSUE THREAD

**Issue by advisorita** [facebookincubator/GeoLift#37]
I followed the walkthrough and got this error below at the step of Power Analysis and Market Selection. Can someone help?

Attempting to load the environment ‘package:tidyr’
Error in { : 
task 1 failed - "Problem while computing `trt_time = replace_na(trt_time,
Inf)`.
Caused by error in `stop_vctrs()`:
! Can't convert from `replace` <double> to `data` <integer> due to loss of precision.

**Comment by ArturoEsquerra** [comment]
Hi @advisorita! This is caused by a recent change in `tidyr`, you can find more on this issue and how to solve it [here](https://github.com/facebookincubator/GeoLift/issues/33)

**Comment by max-kozlowski** [comment]
Hello @ArturoEsquerra 👋 

I'm running into similar issue, even though I did set tidyr to `tidyr_1.1.4`. Strangely, setting to the older version of the library allowed me to run `NumberLocations` function, but I'm still getting an error while trying to run `GeoLiftPowerFinder`.

This is the error I'm getting:

```
Setting up cluster.
Importing functions into cluster.
Finding the best markets for your experiment.
Deterministic setup with 2 locations in treatment.
Error in { : 
  task 1 failed - "Problem while computing `trt_time = replace_na(trt_time, Inf)`.
Caused by error in `stop_vctrs()`:
! Can't convert from `replace` <double> to `data` <integer> due to loss of precision.
• Locations: 1"
```

**Comment by ArturoEsquerra** [comment]
Hi @max-kozlowski! Thanks for reaching out to us.

Could you share more information about your R session to help you troubleshoot this issue? The output from `sessionInfo()` should be more than enough! Also, are you experiencing this issue with the test dataset?

Thanks!
Arturo

**Comment by max-kozlowski** [comment]
Hi @ArturoEsquerra 👋  thanks for a quick response!
After I restarted my laptop, all functions started working 🤔  Not sure why is that but all seems to be fine now.

Thanks!
Max

**Comment by ArturoEsquerra** [comment]
Hi @max-kozlowski! I'm glad to hear that the package is up and working again. If you have any other issues, just let us know!

Best,
Arturo
