### ISSUE TITLE
Long Path issue when installing packages

### ISSUE THREAD

**Issue by alexeyternavskiy** [facebookincubator/GeoLift#46]
Issue happens at the last stage of installing the GeoLift package, where several errors with "path too long" appear. Please see below:
[GeoLift.txt](https://github.com/facebookincubator/GeoLift/files/8288672/GeoLift.txt)

**Comment by kyass** [comment]
Having the same issue

**Comment by kyass** [comment]
Update, one workaround that works is to skip building the package.

> install_github("facebookincubator/GeoLift", build = FALSE)

**Comment by NicolasMatrices-v2** [comment]
Hi, could you share the output of sessionInfo() in your R session please?
Thanks

**Comment by yulisong** [comment]
Hi @NicolasMatrices-v2, 


I've debugged the **install_github()** and tried many ways to install GeoLift. Eventually, I found that, if we could remove the _"*/website/website/node_modules/"_ folder before unzipping (which caused most unwanted warnings) and update the **rlang** package to the newest version before installing GeoLift, ideally(ignoring some cases such as bad network issue), the package can be installed successfully without warnings or errors. 

I realize the _"*/website/website/node_modules/"_ folder is important for building the website but it may make users confused. I was wondering if you have any plan on making the installation more user-friendly while not influencing the website. 

Regards,
Yuli

**Comment by NicolasMatrices-v2** [comment]
Hi all: @alexeyternavskiy, @kyass, @robrady, @yulisong !

Thank you very much for your helpful insight Yuli!
We have managed to reproduce the error and have a PR ready to fix it (https://github.com/facebookincubator/GeoLift/pull/61).

While we finish the review, would you mind trying to install GeoLift from that branch? Just run:

```
remotes::install_github("facebookincubator/GeoLift", branch = "vignette_updates")
```

And please let us know how that goes! cc. @ArturoEsquerra

**Comment by yulisong** [comment]
Hi @NicolasMatrices-v2, thank you so much for your work! It works perfect now.

**Comment by NicolasMatrices-v2** [comment]
Closing out as this has been resolved.  Feel free to reopen if you see the issue occurring again!
