### ISSUE TITLE
Error in utils::download.file

### ISSUE THREAD

**Issue by xybi200666** [facebookincubator/GeoLift#53]
I successfully reinstalled the GeoLift on one of my computer yesterday. I tried to install it on another computer today, but I got the following error message. Please advice how I should solve this issue. THANKS!

Downloading GitHub repo facebookincubator/GeoLift@HEAD
Error in utils::download.file(url, path, method = method, quiet = quiet,  :
  cannot open URL 'https://api.github.com/repos/facebookincubator/GeoLift/tarball/HEAD'

**Comment by NicolasMatrices-v2** [comment]
Hi @xybi200666.  Could you please share a reproducible example of what you are doing and your sessionInfo() please?

**Comment by ArturoEsquerra** [comment]
Hi @xybi200666, thanks for reaching out to us! 

Could you try running the following line to change the R session download file method:
`options(download.file.method = "wininet")`

If that doesn't work I would also recommend trying out libcurl with:
`options(download.file.method = "libcurl")`

Please let us know if it works!

**Comment by xybi200666** [comment]
@NicolasMatrices-v2 @ArturoEsquerra 
Thanks for your help. I tried both downloading options yesterday before I created this issue, but didn't work. Please see the sessionInfo() and error messages below. 

The computer I successfully installed is Mac. The one with error is PC. 

![image001](https://user-images.githubusercontent.com/44693571/159743649-645908e2-83ea-45f6-a4fb-a52cedc6a7a8.png)
![image002-2](https://user-images.githubusercontent.com/44693571/159743790-8e379550-cc56-4376-af45-b131c1e41432.png)

**Comment by ArturoEsquerra** [comment]
Hi again @xybi200666. Unfortunately we've been unable to replicate this error. But it seems that [enabling TLS 1.2](https://github.com/r-lib/remotes/issues/130) has helped Windows users with this issue. 

Click Start > type in "Internet Options" > click "Internet options" > Go to "Advanced" and check TLS 1.2 box. 

Could you try that out and see if it works?

**Comment by xybi200666** [comment]
Hi again @ArturoEsquerra , unfortunately I don't see the "Advanced" tab from "Internet options" on my company PC. 

However, this issue only happens when I installed the most recent version of GeoLift. When I installed the V2.2.2, it runs ok without any issues. 

Any thought?

**Comment by ArturoEsquerra** [comment]
Hi @xybi200666,

We could try installing the package through the .tar.gz file. Here's a link to download it:

[GeoLiftv2.3.7.tar.gz](https://drive.google.com/file/d/1afumk5-yJeGbbgxNwOhNmCmI-xUuUXc3/view?usp=sharing)

[This website](https://riptutorial.com/r/example/5556/install-package-from-local-source) goes through some of the different available approaches to install a package.

Please let us know if it works!

**Comment by xybi200666** [comment]
@ArturoEsquerra  Thank you so much for your help. The package can be installed successfully now. 

Here is the code I used to install. I need to use type="source", otherwise, I got the error below. Again, thanks much!

install.packages("~/GeoLift_2.3.7.tar", repos = NULL, type="source")

Error in install.packages : type == "both" cannot be used with 'repos = NULL'
