### ISSUE TITLE
Issue: Selecting Geos

### ISSUE THREAD

**Issue by ilaria-giunti** [facebookincubator/GeoLift#54]
Hi there,
I'm having some issues selecting the number of geos to include in the test group.

This is my script:

`resultsNum <- NumberLocations(data = GeoTestData_PreTest, Y_id = "Y", location_id = "location", time_id = "time", n_sim = 500, treatment_periods = 15,# test lenght will be 15 days, if you are not sure enter a list of possible values plot = TRUE, power = 0.8, alpha = 0.1, fixed_effects = TRUE, ProgressBar = TRUE)`

Each time I try running this scripts I was faced with this error:

```
task 1 failed - "Problem while computing `trt_time = replace_na(trt_time, Inf)`.
Caused by error in `stop_vctrs()`:
! Can't convert from `replace` <double> to `data` <integer> due to loss of precision.
• Locations: 1"
```

I'm not able to understand why it's happening
Can anybody help me?

**Comment by NicolasMatrices-v2** [comment]
Hi @ilaria-giunti ! This is a known issue related to tidyr's update to 1.2.0.  For the time being, please downgrade tidyr to the previous 1.4 version.  You can find more details in this issue https://github.com/facebookincubator/GeoLift/issues/33. Cheers,

**Comment by ilaria-giunti** [comment]
@NicolasMatrices-v2 @ArturoEsquerra how should i decide how many geos to include in treatment group?
