### ISSUE TITLE
Understand of the GeoLift model

### ISSUE THREAD

**Issue by ilaria-giunti** [facebookincubator/GeoLift#58]
Hi there,

I was able to run my first model with Geolift but I have a few questions for you.

1) When I set up the model, can I use it for both these kinds of experiments?
- Increase in budget spending for a campaign/channel that is already running
- Test a new channel/campaign 

 2) When I use the horizon variable, it showed up this error:
Errore in GeoLiftPower.search(data = GeoTestData_PreTest, treatment_periods = c(15),  : 
  argomento non utilizzato (horizon = 50)

Can you explain to me why?

**Comment by NicolasMatrices-v2** [comment]
Hi @ilaria-giunti ! 

Answering your questions:
1. Yes you can use it for both types of experiments.  For the case when you would like to test a new channel/campaign, you se up a standard GeoLift test, as in the walkthrough we have.  For that case, Chicago and Portland will be the locations that will have investment, and the others will not.  If you would like to test a channel/campaign that is already running, you can also do it in the same way! However, something we've seen that works well (for business reasons) is to run a negative GeoLift, and keep investment away from the treatment.  That way you keep on running media in the majority of the locations that you would like to test and you determine what is the opportunity cost of running ads for that channel in the treatment.

2. We suggest you do not use the GeoLiftPower.search method, as it will be deprecated in GeoLift 4.0.0 and use GeoLiftMarketSelection instead (as seen in the Walkthrough).  If you would still like to use GeoLiftPower.search, you can change the horizon parameter to the lookback_window parameter, it achieves the same goal (just do ?GeoLiftPower.search for more details).

Please feel free to post in our FB group if you have further questions (https://www.facebook.com/groups/fbgeolift/).

Best!

**Comment by ilaria-giunti** [comment]
Hi, @NicolasMatrices-v2 thanks for answering me!

What do you mean by negative Geolift? Can you explain me deeper?

**Comment by ArturoEsquerra** [comment]
Hi @ilaria-giunti! The most popular type of GeoLift experiment consists of delivering the treatment to our test locations and holding-out the control regions from receiving that treatment. This typically means that the population that won't receive the treatment will be larger than the one that does get it. In contrast, a Negative GeoLift is simply an experiment where we switch things up: the test regions won't receive the treatment while the controls will get it.

**Comment by ilaria-giunti** [comment]
How can I run a negative GeoLift?
