### ISSUE TITLE
Speed up calculations using graphics card with GeoLift

### ISSUE THREAD

**Issue by sohammarin** [facebookincubator/GeoLift#72]
## Is your feature request related to a problem? Please describe.
GeoLiftMarketSelection takes a long time to run specially when increasing lookback_window and treatment_period values. Is it possible to speed up these calculations using a GPU?

## Describe the solution you'd like
Would ideally like to specify device to speed up calculations on. 

## Describe alternatives you've considered
I have tried setting parallel_setup = "parallel" but this did not have a significant improvement in runtime.

**Comment by ArturoEsquerra** [comment]
Hi @sohammarin! Thanks for reaching out to us. This is a very interesting idea that we haven't actively explored before. I've added it to our Feature Requests here: https://github.com/facebookincubator/GeoLift/projects/1#card-84669647
