### ISSUE TITLE
Speed up the GeoLiftMarketSelection function

### ISSUE THREAD

**Issue by yulisong** [facebookincubator/GeoLift#74]
Hi @NicolasMatrices-v2 @ArturoEsquerra, sorry that I'm coming to add your work load again.

As @sohammarin suggest, I've also met the problem that the function is relatively slow. I've tried to profile GeoLiftMarketSelection() function using the **profvis** package and realized that a huge amount of time is spent on the `GetCorrel()` function. I've check further and realized that `GetCorrel()` function has done some unnecessary work to calculate the correlation score. It will be much faster to use the `cor()` function in base package directly instead of calling the `MarketMatching::best_matches()` function. And I think it might be the easiest part to change and the most obvious part to improve the computation efficiency. 

Regards,
Yuli

**Comment by ArturoEsquerra** [comment]
Hi @yulisong! Thanks for checking this out and sharing this important information with us. We'll look into them and will optimize the code. In the meantime, it's important to mention that while newer SCM methods (like the ones we use in GeoLift) are more robust against the curse of dimensionality, having too many locations in the pool of controls can be counterproductive. Therefore, in cases where `N` is very large, it's highly recommended to pre-process the data-set.

Best,
Arturo

**Comment by yulisong** [comment]
Hi @ArturoEsquerra, thank you for your quick response! I can always expect your team's quick support :)

I totally agree that we need to control the pool of controls. But I've got other two questions currently. Are there any sizes of `N` that you would suggest? Also, I was wondering if pre-processing the data means looking at the time series plot and remove those markets with different trend only. Thank you!

Regards,
Yuli

**Comment by NicolasMatrices-v2** [comment]
Hi @yulisong! Answering your Qs below:

> Are there any sizes of N that you would suggest?

It depends on the amount of total locations you have, the data and the particular scenario.  A good N usually lies between the 15% and 30% conversion share threshold.  In terms of total locations, we suggest going with less than 100 locations and more than 20.  Using more than 200 locations in GeoLift could lead to the issues Arturo has mentioned above.  

> Also, I was wondering if pre-processing the data means looking at the time series plot and remove those markets with different trend only.

In this case, I think he was referring to reducing the total locations to a manageable number.  You have a couple of options:
- Excluding locations that represent a low share of total conversions, as they will probably not be very important within the synthetic control and if chosen as part of the treatment it will probably be harder to detect an effect over them, given their low conversion count.
- Aggregate locations up to a higher level of granularity (i.e. zips -> city -> states).  This is usually the best option as it reduces the amount of locations without losing any information in the process.

Also, just built a PR to tackle the correlations issue you mentioned. Thanks for this valuable feedback!! I'll let you know when its landed.

**Comment by yulisong** [comment]
Hi @NicolasMatrices-v2, thank you for your answer and it solves my questions very well. I'll close this issue now.
