### ISSUE TITLE
Use weights to manually recreate synthetic control

### ISSUE THREAD

**Issue by max-kozlowski** [facebookincubator/GeoLift#81]
How do I manually recreate synthetic control given the model weighs? Is that simply a weighted sum across the control geos?
I tried doing this a while ago and I couldn't get to the same numbers.

**Comment by ArturoEsquerra** [comment]
Hi @max-kozlowski! As you mentioned, the synthetic control can be calculated as the weighted sum of the units in the pool of controls using the SCM weights. It is important to mention that this calculation will yield the *average* synthetic control unit. If you want to obtain the sum of the synthetic controls (which is what we plot and output in the code), you simply need to multiply that average synthetic unit by the number of test units.
