### ISSUE TITLE
pvalueCalc appears to ignore model when covariates are supplied

### ISSUE THREAD

**Issue by dwkuo** [facebookincubator/GeoLift#82]
## Bug description

When covariates are supplied, GeoLiftMarketSelection() appears to return the same market selection results regardless of whether model="none" or model="Ridge".

I think I traced the source of this problem back to pvalueCalc() which appears to do the heavy-lifting under the hood:
In pre_test_power.R, GeoLiftMarketSelection() calls run_simulations() which calls pvalueCalc(). In lines 286-304, this pvalueCalc code 
```
else if (length(X) > 0) {
    fmla <- as.formula(paste(
      "Y_inc ~ D |",
      sapply(list(X),
        paste,
        collapse = "+"
      )
    ))

    ascm_obj <- augsynth::augsynth(fmla,
      unit = location,
      time = time,
      data = data_aux,
      t_int = treatment_start_time,
      progfunc = "GSYN",
      scm = T,
      fixedeff = fixed_effects
    )
  }
```
appears to set `progfunc = "GSYN"` when covariates are supplied, regardless of what the user originally supplied in the GeoLiftMarketSelection() call. Why, for example, won't it permit `progfunc = "Ridge" ` if supplied by the user?

**Comment by ArturoEsquerra** [comment]
Hi @dwkuo! Thank you very much for highlighting this issue! We've just pushed a fix here: https://github.com/facebookincubator/GeoLift/pull/97
