### ISSUE TITLE
How to decide the CPIC value?

### ISSUE THREAD

**Issue by roh-neenopal** [facebookincubator/GeoLift#85]
## Bug description
 I am running the Geoift model on my data. I have the initial data input of data, location, and sales. How do I know what is the CPIC value?

**Comment by NicolasMatrices-v2** [comment]
Hi @roh-neenopal, 

CPIC stands for Cost Per Incremental Conversion.  Ideally, it should come from the best estimate of incrementality you have for the country you would like to analyze from previous tests.  If you have not run previous experiments, then you could use some form of attributed cost value as a simple replacement.  It basically represents how much you think each extra conversion is costing you.

If you are working with sales, you can input your expected Return On Investment as a CPIC value and it should do the trick.

Closing this issue for now. Feel free to reopen if you would like more details.

**Comment by ArturoEsquerra** [comment]
Hi @roh-neenopal! Adding to @NicolasMatrices-v2 very thorough answer, you could also get CPIC estimates from Marketing Mix Models (MMM). If none of the aforementioned resources are available, a conservative estimate could be used. For instance, if we are selling a $10.00 item and have a $4.00 margin on it, then a super conservative estimate of the CPIC could be $6.00 (the max amount of money we could spend for an additional transaction without financial losses). This conservative value will result in an under-estimated power analysis which would basically provide the upper bound for investment!

**Comment by ilaria-giunti** [comment]
@ArturoEsquerra @NicolasMatrices-v2 should I use another parameter in MarketSelection to calculate the return?

I'm asking because ROAS is Revenue/ Budget Spent, while CPIC is Budget Spent/Conversions
