### ISSUE TITLE
Investment in function design

### ISSUE THREAD

**Issue by ilaria-giunti** [facebookincubator/GeoLift#87]
## Bug description
How do you decide how much should I spend in this experiment?
The statistical significance will be different if I spend 1M or 4M, won't it?

MarketSelection tells me how much I should spend at a minimum for that experiment.
But how will it change if I spend 5k instead of 10? Will it be statistical significant or not?

I.e I decide to use a 10k budget for that experiment and MarketSelection suggests I spend 1k in those target markets.

How will it be if I spend 5k on that experiment instead?

  Please enter a clear and concise description of what the bug is.

## Session information
  Please paste the output after running `sessionInfo()` in your R session.

## Reproduction steps
  Enter steps to reproduce the behavior.

## Expected behavior
  Give a clear and concise description of what you expected to happen.
  
```
Output goes here
```

## Additional context
  Add any other context about the problem here. (like proxy settings, network setup, overall goals, etc.)

**Comment by ArturoEsquerra** [comment]
Hi @ilaria-giunti! That is a very good question. I recommend checking out the power analysis curves from `plot.GeoLiftMarketSelection()` and `#' plot.GeoLiftPower()`. They will show how the power in your experiment increases as a function of the investment. For example, this [power curve](https://facebookincubator.github.io/GeoLift/assets/images/GeoLiftMarketSelection_Plots-2-c14a0cfa3e01ffce89e257496ca58e7e.png) shows that investments below ~$50,000 won't provide significant results, but as you cross this threshold then the effect becomes sufficiently large to always detect it with statistical significance!

**Comment by ilaria-giunti** [comment]
what is the code?
