### ISSUE TITLE
Investment and Lift is daily or total or per region in MarketSelection

### ISSUE THREAD

**Issue by ilaria-giunti** [facebookincubator/GeoLift#89]
## Bug description
When I see investment for market_id 2 equals to 10k, does it mean 10k overall or 10k per day? or per region? 

And for the ATT?
## Session information
  Please paste the output after running `sessionInfo()` in your R session.

## Reproduction steps
  Enter steps to reproduce the behavior.

## Expected behavior
  Give a clear and concise description of what you expected to happen.
  
```
Output goes here
```

## Additional context
  Add any other context about the problem here. (like proxy settings, network setup, overall goals, etc.)

**Comment by ArturoEsquerra** [comment]
Hi @ilaria-giunti! The `Investment` column of the `GeoLiftMarketSelection()` output provides the total estimated investment needed throughout the entire treatment period across all units in the test group! It's important to take into consideration that this calculation relies on an accurate value of the `cpic`
