### ISSUE TITLE
# of geos in treatment group and effect size

### ISSUE THREAD

**Issue by ilaria-giunti** [facebookincubator/GeoLift#98]
## Bug description
- How do I decide how many geos I should have in my control and treatment group? If I have 20 regions I could put 2 or 10 or 15 regions in the treatment group, I could I decide?

- How do I decide the effect size I want? I don't know which is the lift of my campaign and I could be wrong to say (0,0.25,0.50)

```

## Additional context
  Add any other context about the problem here. (like proxy settings, network setup, overall goals, etc.)

**Comment by NicolasMatrices-v2** [comment]
Hi @ilaria-giunti, answering your Qs.

> How do I decide how many geos I should have in my control and treatment group? If I have 20 regions I could put 2 or 10 or 15 regions in the treatment group, I could I decide?

There is no pre-built function in GeoLift that can solve this problem easily for you.  We suggest that you always select treatment sizes that are below half the amount of regions you have (i.e. if you have 20 locations, less than 10).  Regardless of how these are selected (random or deterministic), if you don't specify the N parameter in GeoLiftMarketSelection, we will select a grid of values that will ensure that you will have a sizable sample of treatment sizes.

> How do I decide the effect size I want?

The effect_size parameter only says what is the grid of effects that we will go over to determine what the MDE is.  We suggest you use the default parameters if you do not know what to choose.  It basically depends on how precise you want to be and how much time you have.  A good approximation for GeoLiftMarketSelection is seq(-0.15, 0.15, 0.05), while maybe for GeoLiftPower where you would like to be more precise you could use seq(-0.16, 0.16, 0.02).
